Refactor truelearn
TrueLearnAI/truelearn pull request #55
Opened 2023-04-08 17:10 UTC by yuxqiu

2023-04-08 20:41 UTC, yuxqiu commented
@KD-7 ready for review.

2023-04-09 14:18 UTC, KD-7 commented
> * Define a Root Exception to Insulate Callers from APIs

![image](https://user-images.githubusercontent.com/91730569/230778006-29468371-5a3f-40a8-9560-45032ddee988.png)
We miss a test case covering this

2023-04-09 14:44 UTC, yuxqiu commented
> > * Define a Root Exception to Insulate Callers from APIs
> 
> ![image](https://user-images.githubusercontent.com/91730569/230778006-29468371-5a3f-40a8-9560-45032ddee988.png) We miss a test case covering this

I will fix all the tests in a new PR.

2023-04-10 12:00 UTC, KD-7 requested changes

2023-04-10 13:10 UTC, yuxqiu commented on truelearn/datasets/_base.py
> +        for bytes_read in iter(lambda: file.readinto(write_view), 0):
I suspect this is a bug in Pycharm, as this works fine on my side and passes all the tests.

2023-04-10 13:54 UTC, KD-7 approved these changes

2023-04-10 13:55 UTC, merged

2023-04-10 13:56 UTC, KD-7 commented
@yuxqiu Delete the branch once, the other PRs target branch has been updated to main

2023-04-10 13:58 UTC, yuxqiu commented
Done.